import { c as create_ssr_component } from "../../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return ` <body class="bg-gray-900 text-white"> <nav class="bg-gray-800 p-4"><div class="container mx-auto"><div class="flex justify-between"><a href="#" class="text-2xl font-bold" data-svelte-h="svelte-k14ae0">IgniteHub</a> <div class="flex space-x-4"><a href="#features" class="text-white" data-svelte-h="svelte-8lcj6t">Features</a> <a href="#pricing" class="text-white" data-svelte-h="svelte-jzbslj">Pricing</a> <a href="#contact" class="text-white" data-svelte-h="svelte-2tnv8z">Contact</a></div></div></div></nav>  <section class="bg-gray-800 py-20"><div class="container mx-auto text-center"><h1 class="text-5xl font-extrabold mb-4" data-svelte-h="svelte-1obqiwc">Empowering Your Business</h1> <p class="text-lg mb-8" data-svelte-h="svelte-19f1xe4">IgniteHub provides a suite of applications to service all your
				business needs.</p> <a href="#contact" class="bg-blue-500 text-white py-2 px-6 rounded-full text-lg" data-svelte-h="svelte-97mnur">Get Started</a></div></section>  <section id="features" class="py-20"><div class="container mx-auto"><h2 class="text-3xl font-bold text-center mb-10" data-svelte-h="svelte-luxyak">Features</h2> <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-16"> <div class="bg-gray-800 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-12s89ru">Web Design &amp; Hosting</h3> <p data-svelte-h="svelte-661pb5">Professional web design, management, and hosting
						services to establish your online presence.</p></div>  <div class="bg-gray-800 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-o8esnc">Marketing &amp; Social Media</h3> <p data-svelte-h="svelte-1kr0o1s">Effective marketing strategies and social media
						management to reach your target audience.</p></div>  <div class="bg-gray-800 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-1l3qqbb">Branding</h3> <p data-svelte-h="svelte-1nuh3la">Develop a strong brand identity to build trust and
						recognition in the market.</p></div></div></div></section>  <section id="pricing" class="bg-gray-800 py-20"><div class="container mx-auto text-center"><h2 class="text-3xl font-bold mb-10" data-svelte-h="svelte-qggjsi">Pricing</h2>  <div class="grid grid-cols-1 md:grid-cols-3 gap-16"> <div class="bg-gray-700 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-1hqzkwu">Tier One</h3> <p class="mb-4" data-svelte-h="svelte-tc20e7">Initial web design, continued management, and change
						requests.</p> <a href="#contact" class="bg-blue-500 text-white py-2 px-6 rounded-full text-lg" data-svelte-h="svelte-wneqxw">Contact Us</a></div>  <div class="bg-gray-700 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-1jfo2jw">Tier Two</h3> <p class="mb-4" data-svelte-h="svelte-ko4xew">Includes Tier One services plus graphic design and
						advertising.</p> <a href="#contact" class="bg-blue-500 text-white py-2 px-6 rounded-full text-lg" data-svelte-h="svelte-wneqxw">Contact Us</a></div>  <div class="bg-gray-700 p-6 rounded-lg"><h3 class="text-xl font-bold mb-4" data-svelte-h="svelte-sfn1d6">Tier Three</h3> <p class="mb-4" data-svelte-h="svelte-1v8dfoj">Expands on Tier Two services, adding brand management,
						e-commerce setup, and more.</p> <a href="#contact" class="bg-blue-500 text-white py-2 px-6 rounded-full text-lg" data-svelte-h="svelte-wneqxw">Contact Us</a></div></div></div></section>  <section id="contact" class="py-20"><div class="container mx-auto text-center"><h2 class="text-3xl font-bold mb-10" data-svelte-h="svelte-y3rdmg">Contact Us</h2> <p class="text-lg mb-8" data-svelte-h="svelte-9owymi">Ready to take your business to the next level? Get in touch with
				us today.</p> <a href="mailto:info@ignitehub.com" class="bg-blue-500 text-white py-2 px-6 rounded-full text-lg" data-svelte-h="svelte-vcbuwp">Email Us</a></div></section>  <footer class="bg-gray-800 p-4"><div class="container mx-auto text-center"><p data-svelte-h="svelte-1ehtoau">© 2023 IgniteHub. All rights reserved.</p></div></footer></body>`;
});
export {
  Page as default
};
