extend type Mutation {
  """
  ✨ Insert a single `Newsletter` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newsletter_insert(
    """
    Data object to insert into the table.
    """
    data: Newsletter_Data!
  ): Newsletter_KeyOutput! @fdc_generated(from: "Newsletter", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Orginization` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orginization_insert(
    """
    Data object to insert into the table.
    """
    data: Orginization_Data!
  ): Orginization_KeyOutput! @fdc_generated(from: "Orginization", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Website` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  website_insert(
    """
    Data object to insert into the table.
    """
    data: Website_Data!
  ): Website_KeyOutput! @fdc_generated(from: "Website", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Newsletter` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newsletter_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Newsletter_Data!]!
  ): [Newsletter_KeyOutput!]! @fdc_generated(from: "Newsletter", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Orginization` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  orginization_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Orginization_Data!]!
  ): [Orginization_KeyOutput!]! @fdc_generated(from: "Orginization", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Website` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  website_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Website_Data!]!
  ): [Website_KeyOutput!]! @fdc_generated(from: "Website", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Newsletter` into the table, based on the primary key. Returns the key of the newly inserted `Newsletter`.
  """
  newsletter_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Newsletter_Data!
  ): Newsletter_KeyOutput! @fdc_generated(from: "Newsletter", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Orginization` into the table, based on the primary key. Returns the key of the newly inserted `Orginization`.
  """
  orginization_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Orginization_Data!
  ): Orginization_KeyOutput! @fdc_generated(from: "Orginization", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Website` into the table, based on the primary key. Returns the key of the newly inserted `Website`.
  """
  website_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Website_Data!
  ): Website_KeyOutput! @fdc_generated(from: "Website", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Newsletter` objects into the table, based on the primary key. Returns the key of the newly inserted `Newsletter`.
  """
  newsletter_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Newsletter_Data!]!
  ): [Newsletter_KeyOutput!]! @fdc_generated(from: "Newsletter", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Orginization` objects into the table, based on the primary key. Returns the key of the newly inserted `Orginization`.
  """
  orginization_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Orginization_Data!]!
  ): [Orginization_KeyOutput!]! @fdc_generated(from: "Orginization", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Website` objects into the table, based on the primary key. Returns the key of the newly inserted `Website`.
  """
  website_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Website_Data!]!
  ): [Website_KeyOutput!]! @fdc_generated(from: "Website", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Newsletter` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  newsletter_update(
    """
    The key used to identify the object.
    """
    key: Newsletter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Newsletter_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Newsletter_Data!
  ): Newsletter_KeyOutput @fdc_generated(from: "Newsletter", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Orginization` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  orginization_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Orginization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Orginization_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Orginization_Data!
  ): Orginization_KeyOutput @fdc_generated(from: "Orginization", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Website` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  website_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Website_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Website_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Website_Data!
  ): Website_KeyOutput @fdc_generated(from: "Website", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Newsletter` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  newsletter_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Newsletter_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Newsletter_Data!
  ): Int! @fdc_generated(from: "Newsletter", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Orginization` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  orginization_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Orginization_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Orginization_Data!
  ): Int! @fdc_generated(from: "Orginization", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Website` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  website_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Website_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Website_Data!
  ): Int! @fdc_generated(from: "Website", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Newsletter` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  newsletter_delete(
    """
    The key used to identify the object.
    """
    key: Newsletter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Newsletter_FirstRow
  ): Newsletter_KeyOutput @fdc_generated(from: "Newsletter", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Orginization` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  orginization_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Orginization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Orginization_FirstRow
  ): Orginization_KeyOutput @fdc_generated(from: "Orginization", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Website` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  website_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Website_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Website_FirstRow
  ): Website_KeyOutput @fdc_generated(from: "Website", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Newsletter` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  newsletter_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Newsletter_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Newsletter", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Orginization` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  orginization_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Orginization_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Orginization", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Website` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  website_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Website_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Website", purpose: DELETE_MULTIPLE)
}
