extend type Query {
  """
  ✨ Look up a single `Newsletter` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  newsletter(
    """
    The key used to identify the object.
    """
    key: Newsletter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Newsletter_FirstRow
  ): Newsletter @fdc_generated(from: "Newsletter", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Orginization` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  orginization(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Orginization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Orginization_FirstRow
  ): Orginization @fdc_generated(from: "Orginization", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Newsletter` objects in the table, optionally filtered by `where` conditions.
  """
  newsletters(
    """
    Filter condition to narrow down the query results.
    """
    where: Newsletter_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Newsletter_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Newsletter!]! @fdc_generated(from: "Newsletter", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Orginization` objects in the table, optionally filtered by `where` conditions.
  """
  orginizations(
    """
    Filter condition to narrow down the query results.
    """
    where: Orginization_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Orginization_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Orginization!]! @fdc_generated(from: "Orginization", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table, optionally filtered by `where` conditions.
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
