# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  orginization_insert(
    data: {id: "11111111222233334444555555555555", createdAt: "2025-03-05", name: "", status: "", updatedAt: "2025-03-05"}
  )
}